nop:
  debug: true
  orm:
    init-database-schema: true

  datasource:
    driver-class-name: org.h2.Driver
    jdbc-url: jdbc:h2:./db/test
    username: sa
    password:
    #driver-class-name: com.mysql.cj.jdbc.Driver
    #jdbc-url: jdbc:mysql://127.0.0.1:3306/dev?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    #username: nop
    #password: nop-test
    metrics-enabled: true
    max-size: 20


quarkus:
  log:
    level: INFO

    category:
      "io.nop.core":
        level: INFO
      "io.nop.dao.jdbc":
        level: ERROR